package buildsrc.convention

import buildsrc.CompileGlslTask

// Treats src/main/glsl as a source directory of the main source set, exactly
// like src/main/kotlin and src/main/java: `compileSpirv` is its compile task
// (GLSL -> SPIR-V) and the generated bytecode is registered as part of the
// source set's output, so it lands in the jar as `shaders/<name>.spv` and is on
// the runtime and test classpaths. Only the GLSL sources are committed.
//
// Requires `glslc` (shaderc) or `glslangValidator` to be installed.
plugins {
    kotlin("jvm")
}

val glslDir = layout.projectDirectory.dir("src/main/glsl")
val spirvRootDir = layout.buildDirectory.dir("generated/spirv/main")

val compileSpirv = tasks.register<CompileGlslTask>("compileSpirv") {
    group = "build"
    description = "Compiles src/main/glsl shaders into SPIR-V resources."
    glslSourceDir.fileValue(glslDir.asFile)
    outputDir.fileValue(spirvRootDir.get().dir("shaders").asFile)
}

sourceSets.named("main") {
    // Register the GLSL directory the same way Kotlin/Java source dirs are
    // registered, so it is part of the source set's structure and conventions.
    val glslSource = project.objects.sourceDirectorySet("glsl", "GLSL shader sources")
    glslSource.srcDir(glslDir.asFile)
    allSource.source(glslSource)

    // The compiled SPIR-V joins the module's output: the jar picks it up under
    // shaders/ and the test/runtime classpaths see it too. Declaring compileSpirv
    // as its producer makes every consumer (jar, tests) depend on the task.
    output.dir(mapOf("builtBy" to compileSpirv), spirvRootDir.get().asFile)
}
